//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public string Marca { get; set; }
        public string Model { get; set; }
        public int Pret { get; set; }
        public int An_fabricatie { get; set; }
        public int Km { get; set; }
        public string Culoare { get; set; }
        public string Cutie { get; set; }
        public string Image { get; set; }
    }
}
